import streamlit as st
import ccxt
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import time

# Configuração da Página do Streamlit
st.set_page_config(
    page_title="BRICSVAULT PORTAL SMC",
    page_icon="🏦",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- REPOSITÓRIO INTERNO DE TRADUÇÃO (i18n) ---
# Mapeamento completo dos textos para os 6 idiomas (Português-BR incluso como padrão)
DICIONARIO_LINGUAS = {
    "Português (BR)": {
        "titulo": "🏦 BRICSVAULT PORTAL - Motor de Smart Money Concepts (SMC)",
        "config_globais": "⚙️ Configurações Globais",
        "selecione_cripto": "Selecione Qualquer Criptomoeda (/USDT):",
        "tempo_grafico": "Tempo Gráfico:",
        "modo_vivo": "Ativar Monitoramento em Tempo Real",
        "intervalo_refresh": "Intervalo de Atualização (Segundos):",
        "preco_spot": "Preço Spot Real",
        "variacao_24h": "Variação 24h (Exchange)",
        "stop_atr": "Preço Stop ATR",
        "fib_niveis_titulo": "📐 Níveis Críticos de Retração de Fibonacci (Ciclo Atual)",
        "matriz_detalhada": "📊 Matriz Detalhada de Momentum e Exaustão",
        "compra_forte": "🟢 COMPRA FORTE (SMC + FIBONACCI ALINHADOS)",
        "venda_forte": "🔴 VENTA FORTE (SMC + FIBONACCI ALINHADOS)",
        "neutro": "🟡 NEUTRO (AGUARDAR SMC)",
        "erro_dados": "Dados históricos insuficientes nesta Exchange para calcular a confluência estrutural SMC. Escolha outro Ativo ou reduza o Tempo Gráfico.",
        "fib_nomes": ["0.0% (MÁXIMA)", "23.6%", "38.2% (Fronteira Premium)", "50.0% (Equilíbrio)", "61.8% (Golden Ratio / Desconto)", "78.6%", "100.0% (MÍNIMA)"],
        "fib_posicoes": ["Topo do Ciclo", "Retração Rasa", "Zona de Carga Vendedora", "Preço Justo", "Zona de Compra Institucional", "Retração Profunda", "Fundo do Ciclo"],
        "ctx_desconto": "Ativo posicionado em Zona de Desconto de Fibonacci (Excelente risco/retorno para Institucionais).",
        "ctx_premium": "Ativo posicionado em Zona Premium de Fibonacci (Preço esticado, propício para realização de lucro).",
        "ctx_neutro": "Preço em zona neutra de equilíbrio de Fibonacci (Fair Value Zone)."
    },
    "Inglés (EN)": {
        "titulo": "🏦 BRICSVAULT PORTAL - Smart Money Concepts (SMC) Engine",
        "config_globais": "⚙️ Global Settings",
        "selecione_cripto": "Select Any Cryptocurrency (/USDT):",
        "tempo_grafico": "Timeframe:",
        "modo_vivo": "Enable Real-Time Monitoring",
        "intervalo_refresh": "Refresh Interval (Seconds):",
        "preco_spot": "Real Spot Price",
        "variacao_24h": "24h Variation (Exchange)",
        "stop_atr": "ATR Stop Price",
        "fib_niveis_titulo": "📐 Critical Fibonacci Retraction Levels (Current Cycle)",
        "matriz_detalhada": "📊 Detailed Momentum & Exhaustion Matrix",
        "compra_forte": "🟢 STRONG BUY (SMC + FIBONACCI ALIGNED)",
        "venda_forte": "🔴 STRONG SELL (SMC + FIBONACCI ALIGNED)",
        "neutro": "🟡 NEUTRAL (AWAIT SMC)",
        "erro_dados": "Insufficient historical data on this Exchange to calculate SMC structural confluence. Choose another Asset or reduce the Timeframe.",
        "fib_nomes": ["0.0% (MAXIMUM)", "23.6%", "38.2% (Premium Frontier)", "50.0% (Equilibrium)", "61.8% (Golden Ratio / Discount)", "78.6%", "100.0% (MINIMUM)"],
        "fib_posicoes": ["Cycle Top", "Shallow Retraction", "Seller Load Zone", "Fair Price", "Institutional Buy Zone", "Deep Retraction", "Cycle Bottom"],
        "ctx_desconto": "Asset positioned in Fibonacci Discount Zone (Excellent risk/reward for Institutionals).",
        "ctx_premium": "Asset positioned in Fibonacci Premium Zone (Price stretched, suitable for profit-taking).",
        "ctx_neutro": "Price in neutral Fibonacci equilibrium zone (Fair Value Zone)."
    },
    "Español (ESP)": {
        "titulo": "🏦 BRICSVAULT PORTAL - Motor de Smart Money Concepts (SMC)",
        "config_globais": "⚙️ Configuraciones Globales",
        "selecione_cripto": "Seleccione Cualquier Criptomoneda (/USDT):",
        "tempo_grafico": "Período de Tiempo:",
        "modo_vivo": "Activar Monitoreo en Tiempo Real",
        "intervalo_refresh": "Intervalo de Actualización (Segundos):",
        "preco_spot": "Precio Spot Real",
        "variacao_24h": "Variación 24h (Exchange)",
        "stop_atr": "Precio Stop ATR",
        "fib_niveis_titulo": "📐 Niveles Críticos de Retracción de Fibonacci (Ciclo Actual)",
        "matriz_detalhada": "📊 Matriz Detallada de Momentum y Agotamiento",
        "compra_forte": "🟢 COMPRA FUERTE (SMC + FIBONACCI ALINEADOS)",
        "venda_forte": "🔴 VENTA FUERTE (SMC + FIBONACCI ALINEADOS)",
        "neutro": "🟡 NEUTRO (ESPERAR SMC)",
        "erro_dados": "Datos históricos insuficientes en esta Exchange para calcular la confluencia estrutural SMC. Elija otro Activo o reduzca el Tiempo Gráfico.",
        "fib_nomes": ["0.0% (MÁXIMA)", "23.6%", "38.2% (Frontera Premium)", "50.0% (Equilibrio)", "61.8% (Golden Ratio / Descuento)", "78.6%", "100.0% (MÍNIMA)"],
        "fib_posicoes": ["Techo del Ciclo", "Retracción Superficial", "Zona de Carga Vendedora", "Precio Justo", "Zona de Compra Institucional", "Retracción Profunda", "Fondo del Ciclo"],
        "ctx_desconto": "Activo posicionado en Zona de Descuento de Fibonacci (Excelente riesgo/beneficio para Institucionales).",
        "ctx_premium": "Activo posicionado en Zona Premium de Fibonacci (Precio estirado, propicio para toma de ganancias).",
        "ctx_neutro": "Precio en zona neutral de equilibrio de Fibonacci (Fair Value Zone)."
    },
    "中文 (CH)": {
        "titulo": "🏦 BRICSVAULT 门户 - 聪明的钱概念 (SMC) 引擎",
        "config_globais": "⚙️ 全局设置",
        "selecione_cripto": "选择任何加密货币 (/USDT):",
        "tempo_grafico": "时间框架:",
        "modo_vivo": "启用实时监控",
        "intervalo_refresh": "刷新间隔（秒）:",
        "preco_spot": "实时现货价格",
        "variacao_24h": "24小时涨跌幅 (交易所)",
        "stop_atr": "ATR 止损价",
        "fib_niveis_titulo": "📐 关键斐波那契回撤水平（当前周期）",
        "matriz_detalhada": "📊 动量与衰竭详细矩阵",
        "compra_forte": "🟢 强力买入 (SMC + 斐波那契共振)",
        "venda_forte": "🔴 强力卖出 (SMC + 斐波那契共振)",
        "neutro": "🟡 中性 (等待 SMC 信号)",
        "erro_dados": "该交易所的历史数据不足，无法计算 SMC 结构共振。请选择其他资产或缩短时间框架。",
        "fib_nomes": ["0.0% (最高点)", "23.6%", "38.2% (溢价边界)", "50.0% (平衡点)", "61.8% (黄金分割 / 折扣区)", "78.6%", "100.0% (最低点)"],
        "fib_posicoes": ["周期顶部", "浅幅回撤", "卖家压盘区", "合理价格", "机构买入区", "深幅回撤", "周期底部"],
        "ctx_desconto": "资产处于斐波那契折扣区（对机构而言极佳 Risk/Reward）。",
        "ctx_premium": "资产处于斐波那契溢价区（价格拉升过高，适合获利了结）。",
        "ctx_neutro": "价格处于斐波那契中性平衡区 (Fair Value Zone)。"
    },
    "Русский (RUS)": {
        "titulo": "🏦 BRICSVAULT ПОРТАЛ - Алгоритм Smart Money Concepts (SMC)",
        "config_globais": "⚙️ Глобальные настройки",
        "selecione_cripto": "Выберите криптовалюту (/USDT):",
        "tempo_grafico": "Таймфрейм:",
        "modo_vivo": "Включить мониторинг в реальном времени",
        "intervalo_refresh": "Интервал обновления (сек):",
        "preco_spot": "Текущая спотовая цена",
        "variacao_24h": "Изменение за 24ч (Exchange)",
        "stop_atr": "Цена ATR Stop",
        "fib_niveis_titulo": "📐 Критические уровни коррекции Фибоначчи (Текущий цикл)",
        "matriz_detalhada": "📊 Подробная матрица импульса и истощения",
        "compra_forte": "🟢 АКТИВНОЕ ПОКУПКА (SMC + ФИБОНАЧЧИ СОГЛАСОВАНЫ)",
        "venda_forte": "🔴 АКТИВНОЕ ПРОДАЖА (SMC + ФИБОНАЧЧИ СОГЛАСОВАНЫ)",
        "neutro": "🟡 НЕЙТРАЛЬНО (ОЖИДАНИЕ SMC)",
        "erro_dados": "Недостаточно исторических данных на этой бирже для расчета структурного слияния SMC. Выберите другой актив или уменьшите таймфрейм.",
        "fib_nomes": ["0.0% (МАКСИМУМ)", "23.6%", "38.2% (Премиум граница)", "50.0% (Равновесие)", "61.8% (Золотое сечение / Дисконт)", "78.6%", "100.0% (МИНИМУМ)"],
        "fib_posicoes": ["Пик цикла", "Мелкая коррекция", "Зона нагрузки продавцов", "Справедливая цена", "Институциональная зона покупки", "Глубокая коррекция", "Дно цикла"],
        "ctx_desconto": "Актив находится в дисконтной зоне Фибоначчи (Отличное соотношение риск/прибыль для крупных игроков).",
        "ctx_premium": "Актив находится в премиум-зоне Фибоначчи (Цена завышена, подходит для фиксации прибыли).",
        "ctx_neutro": "Цена находится в нейтральной зоне равновесия Фибоначчи (Fair Value Zone)."
    },
    "Français (FR)": {
        "titulo": "🏦 BRICSVAULT PORTAL - Moteur Smart Money Concepts (SMC)",
        "config_globais": "⚙️ Paramètres Globaux",
        "selecione_cripto": "Sélectionnez une Crypto-monnaie (/USDT):",
        "tempo_grafico": "Unités de Temps:",
        "modo_vivo": "Activer le Suivi en Temps Réel",
        "intervalo_refresh": "Intervalle de Rafraîchissement (Secondes):",
        "preco_spot": "Prix Spot Réel",
        "variacao_24h": "Variation 24h (Exchange)",
        "stop_atr": "Prix Stop ATR",
        "fib_niveis_titulo": "📐 Niveaux Critiques de Retracement de Fibonacci (Cycle Actuel)",
        "matriz_detalhada": "📊 Matrice Détaillée du Momentum & Épuisement",
        "compra_forte": "🟢 ACHAT FORT (SMC + FIBONACCI ALIGNÉS)",
        "venda_forte": "🔴 VENTE FORTE (SMC + FIBONACCI ALIGNÉS)",
        "neutro": "🟡 NEUTRE (ATTENTE SMC)",
